export const verified = [
  { c: 'MIDGIFT-bf25b7', s: 'verified' },
  { c: 'DINOBOX-54d57b', s: 'verified' },
  { c: 'DINOVOX-cb2297', s: 'verified' },
  { c: 'DINOGAZ-c723ac', s: 'verified' },
  { c: 'DHPF-230c6b', s: 'verified' },
  { c: 'DRIFTERS-efd96c', s: 'verified' },
  { c: 'FCHIPS-c9d584', s: 'verified' },
  { c: 'FRAMEITFC-4d1023', s: 'verified' },
  { c: 'KROQWT-b6b8e5', s: 'verified' },
  { c: 'OPIUMPASS-ff95cf', s: 'verified' },
  { c: 'ORBS-096feb', s: 'scam' },
  { c: 'QWTCARDS-17f15b', s: 'verified' },
  { c: 'QWTCOINS-27203b', s: 'verified' },
  { c: 'QWTEVCARS-d0cb53', s: 'verified' },
  { c: 'TIKAWLITE-04614b', s: 'verified' },
  { c: 'TIKAWULTRA-e6592a', s: 'verified' },
  { c: 'XPACHIEVE-5a0519', s: 'verified' },
  { c: 'TRT-956a03', s: 'verified' },
  { c: 'TAVERN-e9b9d6', s: 'verified' }
];
